name: build-push-sign

env:
  REGISTRY: ghcr.io

on:
  workflow_dispatch:
    inputs:

concurrency:
  group: ci-build-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest 
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
        
      - name: Get config file 
        run: |
          curl -H "Authorization: token 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" -o ./config.json -s https://raw.githubusercontent.com/nirmata/reusable-workflows/NDEV-19853/tags/kubectl_config.json
          cat ./config.json

      - name: Set matrix variable
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(jq -c . < ./config.json)"

  tag-scan-nightly:
    needs: configure
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - name: Print Matrix
        run: |
          # Print the matrix value from the previous job
          echo "The matrix value from the previous job is: ${{ needs.configure.outputs.matrix }}"

      - name: Debug Output
        run: echo "${{ needs.configure.outputs.matrix }}"


      - name: Image scanning
        id: scan
        uses: nirmata/reusable-workflows/.github/actions/nightly-scanning@NDEV-19853
        with:
          tag: ${{ matrix.kubectl-tags }}
          repo: ${{ github.repository }}
          github_password: ${{ secrets.GITHUB_TOKEN }}
          pcc_url: ${{ secrets.PCC_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
